import type { Metadata } from "next";
import { Link } from "@/i18n/navigation";
import PageHeader from "@/components/PageHeader";

export const metadata: Metadata = {
  title: "Terms of Service | TutorForge",
  description: "Terms and conditions for using the TutorForge AI voice tutoring platform.",
};

const sections = [
  {
    title: "Acceptance of terms",
    body: "By accessing or using TutorForge, you agree to these Terms of Service and our Privacy Policy. If you do not agree, do not use the platform.",
  },
  {
    title: "Service description",
    body: "TutorForge provides AI-powered voice tutoring tools, including customizable companions, live voice sessions, transcripts, summaries, and learning analytics. Features may change over time as the product evolves.",
  },
  {
    title: "Account responsibilities",
    body: "You are responsible for maintaining the security of your account, for activity under your account, and for providing accurate registration information. You must be legally able to enter into these terms in your jurisdiction.",
  },
  {
    title: "Acceptable use",
    body: "You agree not to misuse TutorForge, including attempting to access other users' private data, uploading harmful content, interfering with platform operations, or using the service for unlawful purposes. Public companions must not contain abusive, misleading, or infringing material.",
  },
  {
    title: "AI-generated content",
    body: "Voice responses, summaries, and quizzes are generated by AI and may contain errors. TutorForge is a learning aid, not a substitute for professional advice, formal instruction, or certified tutoring in regulated fields.",
  },
  {
    title: "Subscriptions and billing",
    body: "Paid plans, if offered, are billed through Clerk. Plan limits, pricing, and features are described on the Pricing and Subscription pages. Fees are non-refundable except where required by law or explicitly stated otherwise.",
  },
  {
    title: "Intellectual property",
    body: "You retain rights to content you create, such as companion configurations and session transcripts. You grant TutorForge the rights needed to host, process, and display that content to provide the service, including showing public companions to other users.",
  },
  {
    title: "Termination",
    body: "We may suspend or terminate access if these terms are violated or if necessary to protect the platform. You may stop using TutorForge at any time.",
  },
  {
    title: "Disclaimer",
    body: 'TutorForge is provided "as is" without warranties of any kind, to the fullest extent permitted by law. We do not guarantee uninterrupted service or error-free AI output.',
  },
  {
    title: "Contact",
    body: "Questions about these terms can be directed to the TutorForge project support contact.",
  },
];

const TermsPage = () => {
  return (
    <main>
      <PageHeader
        title="Terms of Service"
        description="Last updated: July 2026. Please read these terms before using TutorForge."
      />

      <div className="flex flex-col gap-4">
        {sections.map(({ title, body }) => (
          <section key={title} className="section-card flex flex-col gap-2">
            <h2 className="text-xl font-semibold">{title}</h2>
            <p className="text-sm leading-relaxed text-muted-foreground">{body}</p>
          </section>
        ))}
      </div>

      <section className="section-card flex flex-wrap gap-3">
        <Link href="/privacy" className="btn-primary">
          Privacy Policy
        </Link>
        <Link
          href="/pricing"
          className="inline-flex items-center rounded-xl border border-border px-4 py-2.5 text-sm font-semibold transition-colors hover:bg-muted"
        >
          Pricing
        </Link>
      </section>
    </main>
  );
};

export default TermsPage;
